[project]
name = "ga-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deap>=1.4.2",
    "sqlalchemy>=2.0.38",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "faker>=37.0.0",
    "ipython>=9.0.1",
]
